### ISSUE TITLE
link dead

### ISSUE THREAD

**Issue by trashbirdecology** [SESYNC-ci/basic-Shiny-lesson#7]
Link provided in the following sentence is 404
> The example below, and many __additional examples__, will open in a new browser window (you may need to prevent your broswer from blocking pop-out windows in order to view the app).

http://shiny.rstudio.com/tutorial/lesson1/#Go%20Further

**Comment by khondula** [comment]
thanks for noticing! looks like rstudio reorganized shiny tutorials website and the list of built in examples is now at the bottom of this page: https://shiny.rstudio.com/tutorial/written-tutorial/lesson1/.

**Comment by qdread** [comment]
Fixed link in 1aa7db2
