### ISSUE TITLE
Exercise 4 solution does not run

### ISSUE THREAD

**Issue by foteinidd** [SESYNC-ci/basic-Shiny-lesson#8]
Exercise 4 solution does not run because of this part:

`  selected_years <- reactive({
    popdata %>%
      filter(NAME == input[['NAME']]) %>%
      filter(
        year >= input[['slider_years']][1],
        year <= input[['slider_years']][2])
  })`

slider_years does not exist (can be replaced with my_xlims) and `filter(NAME == input[['NAME']])`  should be replaced with `filter(NAME == input[['selected_city']])`

**Comment by qdread** [comment]
@khondula fixed this! I tested it and it works. Thanks for bringing this to our attention.
